services:
    db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: admin
      volumes:
        - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata: